AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AsgMinSize:
    Type: Number
    Description: Minimum size of the ASG
    Default: '1'
  AsgMaxSize:
    Type: Number
    Description: Maximum size of the ASG
    Default: '3'
  InstanceType:
    Type: String
    Description: EC2 Instance Type to use
    Default: t3.nano
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      ImageId: !Ref 'LatestAmiId'
      InstanceType: !Ref 'InstanceType'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -xeuo pipefail
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          echo "I have booted"

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Fn::GetAZs: ""
      LaunchConfigurationName: !Ref 'LaunchConfiguration'
      MinSize: !Ref 'AsgMinSize'
      MaxSize: !Ref 'AsgMaxSize'
      DesiredCapacity: !Ref 'AsgMinSize'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
          PropagateAtLaunch: 'true'
